name = "kraken"
version = "0.1.0"
defaultTargets = ["kraken"]

[[lean_lib]]
name = "AsmInterp"

[[lean_lib]]
name = "Kraken"
srcDir = "AsmInterp"
root = "CodeGen"
globs = ["CodeGen"]

[[lean_exe]]
name = "kraken"
root = "Main"
