name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-core:
    name: Build Kraken (as per lean-toolchain)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1

  build-experimental:
    name: Build KrakenExp (4.28.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Override Lean toolchain with 4.28
        run: echo "leanprover/lean4:v4.28.0" > lean-toolchain
      - uses: leanprover/lean-action@v1
